### ISSUE TITLE
Include ID in profile

### ISSUE THREAD

**Issue by freezy** [wohali/ips4-oauth2-server#10]
Any particular reason you're not including the user ID in the returned profile data? I can use the email address, but when the user changes its email at the IPS site, there is no way to recognize the user and a new account will be the result.

**Comment by wohali** [comment]
Many OAuth consumers expect user ID == user email address, which is why the implementation ended up that way. You're right, your email address is not necessarily your unique user ID within IPS4.

Fortunately, adding the user IPS4 user ID # to the profile is pretty simple work (should be a single line of code).

I will add the ID functionality, but ideally I'd be extending the support to provide [OpenID Connect](http://openid.net/connect/) functionality instead - something I've considered but haven't implemented yet because it's a pile of code and there are still more systems that support basic OAuth 2 than support OpenID Connect.

**Comment by freezy** [comment]
Yeah sorry I didn't check the code, mainly because I don't have any IPS4 installation running I could access. I was basically testing a setup from someone else. However, turns out on second try the admin could enable a checkbox somewhere which resulted in the ID field being populated.

Does that make any sense? I'm sorry I don't have any more specifics, but it seems resolved for me now.

**Comment by wohali** [comment]
Ah yeah, all you need to do is enable the user.profile scope. [I do already populate the ID :)](https://github.com/wohali/ips4-oauth2-server/blob/master/interface/oauth/me.php#L44)

**Comment by freezy** [comment]
Got it, thanks!
